# Generated by Django 4.2.6 on 2023-10-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_1',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='home'),
        ),
        migrations.AlterField(
            model_name='comment_5',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.post_5'),
        ),
    ]
