# Generated by Django 4.2.6 on 2023-10-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_1_image_alter_comment_5_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_2',
            name='titel_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment_1',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.post_1'),
        ),
        migrations.AlterField(
            model_name='comment_2',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_2', to='home.post_2'),
        ),
        migrations.AlterField(
            model_name='post_1',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='./static/image'),
        ),
    ]
