# Generated by Django 4.2.6 on 2023-10-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_comment_2_titel_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_5',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='./static/image'),
        ),
    ]
