# Generated by Django 4.2.6 on 2023-10-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_image_post_5_image_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_6',
            name='image_6',
            field=models.ImageField(default='avatar.png', upload_to='./static/gallery'),
        ),
    ]
