# Generated by Django 4.2.6 on 2023-10-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_post_6_image_6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_6',
            old_name='image_6',
            new_name='image_6_1',
        ),
        migrations.AddField(
            model_name='post_6',
            name='image_6_2',
            field=models.ImageField(default='avatar.png', upload_to='./static/gallery'),
        ),
        migrations.AddField(
            model_name='post_6',
            name='image_6_3',
            field=models.ImageField(default='avatar.png', upload_to='./static/gallery'),
        ),
    ]
